_schema: _schema
paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_pages:
    path: src/pages
    name: Src Pages
    icon: pages
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  Blog:
    path: src/content/blog
    glob:
    name: blog
    singular_name:
    icon: article
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: ''
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  src_data:
    path: src/data
    name: Src Data
    icon: chat
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  sample:
    path: src/content/sample
    glob:
    name:
    singular_name:
    icon: notes
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
timezone: America/Sao_Paulo
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
